menu:
  Home: /
  教材: http://hellojs.readbook.tw/
  # Slack: /
  # Hackpad: /


# duoshuo comment
duoshuo: false
duoshuo_name:

# disqus comment
disqus: false
disqus_shortname:

# google analytics
googleTrackId: "UA-74285642-4"
